# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado/lab5_pipeline/lab5_pipeline.srcs/sources_1/ip/InsMem/InsMem.xci
# IP: The module: 'InsMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/lab5_pipeline/lab5_pipeline.srcs/sources_1/ip/InsMem/InsMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InsMem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivado/lab5_pipeline/lab5_pipeline.srcs/sources_1/ip/InsMem/InsMem.xci
# IP: The module: 'InsMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/lab5_pipeline/lab5_pipeline.srcs/sources_1/ip/InsMem/InsMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InsMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
